# Generated by Django 4.0 on 2021-12-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField(unique=True, verbose_name='Полный URL')),
                ('short_url', models.CharField(max_length=80, unique=True, verbose_name='Сокращённый URL')),
                ('session_id', models.CharField(max_length=80, verbose_name='id сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
            ],
        ),
    ]
